### ISSUE TITLE
/dank/null turns sulfur from thermal foundation into invalid item

### ISSUE THREAD

**Issue by tril0byte** [p455w0rd/DankNull#214] opened 2019-09-24 04:06 UTC
reproducible: Yes

DankNull-1.12.2-1.6.77.jar
ThermalFoundation-1.12.2-2.6.3.27

Place a thermalfoundation:material "dustSulfur" into the /dank/null, it turns into an item called "Invalid Item (Destroy)" with a pink icon.  I can remove the invalid item from the /dank/null and carry it in my inventory.  The invalid items also stack.

**Comment by BrockWS** [comment] 2019-09-24 06:54
Use latest version.

Duplicate of #204

**Closed as completed by BrockWS** 2019-09-24 06:54 UTC
Labels: duplicate
