### ISSUE TITLE
DankNull vs AE2 

### ISSUE THREAD

**Issue by Jafi-Jaf** [p455w0rd/DankNull#250] opened 2020-01-03 18:39 UTC
put, but could not get, even the export bus :(

**Comment by bloodscon** [comment] 2020-01-10 18:27
I know on refined storage you need to set to extract on the item in the cubes UI. (Control + Mouse click) on the item

**Comment by cjm721** [comment] 2020-03-28 22:50
Should be fixed by #263

**Closed as completed by cjm721** 2020-03-28 22:50 UTC

**Comment by cjm721** [comment] 2020-03-28 23:33
And duplicate of #244 as well.
