### ISSUE TITLE
HUGE Dupe Bug  (Server Tested: Dw20 1.12.2)

### ISSUE THREAD

**Issue by FactionPvP** [p455w0rd/DankNull#109] opened 2018-05-06 19:13 UTC
With the dank/null you can dupe ME drives, Backpacks, or anything that can store items

Video Link: 
https://youtu.be/vVHuGEyTo4A

**Comment by papakapp** [comment] 2018-05-16 04:21
you can also dupe any block that can be chiseled with chisels and bits.  it converts all bits you walk over into the first type of bit you stuck in it.

1) chisel a diamond block and manually stick the bits it in your dank/null
2) chisel a cobblestone block and walk over the bits
3) profit

**Comment by p455w0rd** [comment] 2018-05-16 14:08
sounds like dupe of #95

**Closed as completed by p455w0rd** 2018-05-16 14:08 UTC
Labels: duplicate
