### ISSUE TITLE
Experiencing issues (crash report) but not actually crashing the system.... (R.A.D.)

### ISSUE THREAD

**Issue by dtoxftw** [p455w0rd/DankNull#253] opened 2020-01-21 17:43 UTC
1.12.2
Rouguelike Adventures and Dungeons: 1.35

Full Report: [https://paste.dimdev.org/inajonobiz.mccrash](https://paste.dimdev.org/inajonobiz.mccrash)

When starting up the game I receive [this message](https://i.imgur.com/g1c1hIk.jpg).  I'm not seeing any issues in-game but am concerned about future use.  Any help is appreciated. Thanks

**Comment by jdratlif** [comment] 2020-01-31 21:52
I'm getting the same problem. It's in a custom mod pack I'm working on. Only happens on client connect to server. Doesn't seem to affect game play, but we haven't done much play testing yet.

It doesn't happen in single player worlds.

**Comment by bux** [comment] 2020-02-12 14:27
Getting the same: https://paste.dimdev.org/inajonobiz.mccrash
Also only when connecting to a server

**Comment by cjm721** [comment] 2020-03-28 22:48
Duplicate of #237

**Closed as completed by cjm721** 2020-03-28 22:48 UTC
