### ISSUE TITLE
[Suggestion] Dyable/Nameable Dank/Nulls

### ISSUE THREAD

**Issue by Darkarma** [p455w0rd/DankNull#79] opened 2018-01-23 18:01 UTC
Want to say, love what you have done with these and they are so useful.

On the other hand I'm finding I'm running into the issue of using more than one, specifically more than one of the same exact type. Would it be possible in some time in the future having the ability to dye Danks so that when using say multiple emerald or diamond tiers, they are distinguishable? Or the other alternative, be able to name them on an Anvil. Either one or both would significantly boost the usefulness of the mod.

Again love this mod!

**Comment by p455w0rd** [comment] 2018-01-23 18:28
you can name them in an anvil..dying..no

**Comment by p455w0rd** [comment] 2018-01-23 18:32
![](http://p455w0rd.net/u/13.31.23-23.01.18.gif)

**Comment by Darkarma** [comment] 2018-01-23 19:06
Thanks, didn't see that in the tutorial I ran across. Very handy!

**Comment by Twisted-Code** [comment] 2019-09-29 18:05
p455w0rd, that doesn't seem to work quite right (anymore?). I just tried renaming one of my emerald Danks, but it reverted to the default name not long afterwards. I think it was after I updated its contents? In any case, it's not working in 1.6.80

**Comment by p455w0rd** [comment] 2019-09-29 18:06
ah...ill look into it..thanks

**Comment by p455w0rd** [comment] 2019-11-17 13:28
![got it working.jif](https://puu.sh/EFA2Q/b52f0f70b5.gif)

**Comment by p455w0rd** [comment] 2019-11-19 22:27
fixed in [this update](https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2829709) - keep in mind that you will need [this version of p455w0rdslib](https://www.curseforge.com/minecraft/mc-mods/p455w0rds-library/files/2829707) as well

**Closed by p455w0rd** 2019-11-19 22:27 UTC
Labels: bug, fixed

**Comment by Twisted-Code** [comment] 2020-01-30 19:46
just a heads up, I ran into a crash (seemingly caused by a mod conflict with the latest Railcraft) when updating to the version of your lib you linked above. I'm about to open a separate issue for it (assuming I don't find it's already been reported. I notice you have 2 new builds...), but if you want to get a head start on it  (I say is if you have nothing better to do... heh, sorry about this), you can read all about it here: Railcraft/Railcraft#1916
edit: This may have been a coincidence from Railcraft's point of view according to what someone on their discord said; before opening an issue, I'm going to try what they suggested doing: update WTLib (and your wireless terminal mod itself) to see if that was the problem. If (as I suspect given what very limited modding experience I have... so this could be completely wrong) you didn't tell FML what the last compatible version of p455w0rd Lib was for WT Lib -I can't imagine you would have unless you read the future and knew the next version of plib would break WTLib BEFORE releasing WTLib-, that might explain why it broke without telling me it was a dependency issue... but I better test (... right after I finish my college assessment) :-)
