### ISSUE TITLE
DankNull ran into an issue

### ISSUE THREAD

**Issue by Wxrlds** [p455w0rd/DankNull#248] opened 2019-12-30 18:09 UTC
Everytime I join our Server Vanilla Fix tells me DankNull runs into issues. Thought you might want to take a look at that.
Log (from Vanilla Fix): https://gist.github.com/Wxrlds/d30465da966009a2a1b1b5ae1f49d18e

**Comment by inspiiree** [comment] 2019-12-31 21:31
Same issue here unfortunately for myself and a friend

**Comment by bloodscon** [comment] 2020-01-10 18:41
check dank null has the correct dependencies for its version had similar report to this after i did an update to mod mode but forgot to update p455w0rd's Library

**Comment by inspiiree** [comment] 2020-01-11 13:51
I actually updated the library too to latest dependacies and still no luck

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cjm721** [comment] 2020-03-28 22:55
Duplicate of #237

**Closed as completed by cjm721** 2020-03-28 22:55 UTC
