### ISSUE TITLE
Conversion Glitch

### ISSUE THREAD

**Issue by Glittersword** [p455w0rd/DankNull#110] opened 2018-05-13 16:01 UTC
I just noticed this when using the Dank/Null in Forever Stranded/Lost Souls

When I put an undamaged Enchanted Item in the the Null and put in a second undamaged item with a different enchantment on it in the Null instead of putting it in a new slot it will stack them together and give you 2 of the first item.  Thus 1 "Projectile Protection 1" and 1 "Unbreaking 1" becomes 2 "Projectile Protection 1"s  After that visit the anvil and you have a real cheap "Projectile Protection 2"

Rinse and repeat.

**Comment by p455w0rd** [comment] 2018-05-16 14:02
dupe of #95

**Closed as completed by p455w0rd** 2018-05-16 14:02 UTC
Labels: duplicate
