### ISSUE TITLE
weird thing don't know how to explain

### ISSUE THREAD

**Issue by ANNOYEDCHERRY** [p455w0rd/DankNull#24] opened 2017-11-19 22:14 UTC
Not sure if this is an issue with the mod recreated it in a test world once but couldn't a second time logged out of world could not log back in. 

clipped it for your viewing pleasure

https://clips.twitch.tv/PunchyGlutenFreeMarrowDuDudu

**Comment by p455w0rd** [comment] 2017-11-19 23:30
i'm not soeing anything wrong?

**Comment by ANNOYEDCHERRY** [comment] 2017-11-19 23:43
gotta get a new clip after stream that was when I couldnt recreated should have watched it fully

**Comment by ANNOYEDCHERRY** [comment] 2017-11-20 03:48
https://clips.twitch.tv/AnimatedRenownedCrabsDeIlluminati


Okay here is the new clip. Like I said not sure if the mod or something random happening

**Comment by p455w0rd** [comment] 2017-11-20 12:43
very odd indeed..i will look into it..thanks for reporting :)

**Comment by p455w0rd** [comment] 2017-11-20 12:57
what version is this? it's not doing this in 1.12.2

**Comment by p455w0rd** [comment] 2017-11-20 13:03
just tried in pwthings (1.10.2) and it doesn't happen either..I'm thinking either outdated mod version or mod interaction..since I am unable to reproduce I'll need to see a log

**Comment by hills1** [comment] 2017-11-24 22:33
I'm having the same issue on occasion.  

I'm running Direwolf20 1.12 v1.10 with the following additional mods:
environmentalcreepers-1.12.1-1.2.1.jar
lostsouls-1.12-1.0.0.jar
torchmaster_1.12.1-1.5.3.43.jar
BiblioCraft[v2.4.3][MC1.12.0].jar
ColossalChests-1.12.2-1.6.8.jar
CyclopsCore-1.12.2-0.10.23.jar

Relevant portion of log: https://pastebin.com/Uq3hvJmv (the issue happens at 16:14:19, "Fatal errors were detected during the transition from SERVER_STOPPING to SERVER_ABOUT_TO_START. Loading cannot continue")

It _might_ be related to a bug where crouch+scroll 'breaks' in an odd way; when that bug occurs, scrolling off of a /dank/null (onto another equipment slot) causes it to revert its selection to a random(?) item (including empty/air slots).  That bug might be triggered by having two /dank/nulls next to each other on the hotbar.  There may be no relation, and I just happen to notice them together because that bug leads me to try to restart my world to fix it.

I'll see if I can reproduce the issue reliably, and if I can I'll try to figure out which mod combination causes it to happen.

**Comment by p455w0rd** [comment] 2017-11-24 22:37
awesome! thank you so much for the detailed report @hills1 :) as far as scrolling issue..no matter how many /dank/nulls, it should only effect things when crouching...I will likely switch this to a user-defined keybind at some point to avoid stuff like this...I won't likely work on anything tonight..i spent ther day manually auguring holes for a solar array job I'm working on..i'm just beat, but i'll do my best to get this figured out before the next DW20 pack update...thanks again :)

**Comment by hills1** [comment] 2017-11-24 22:54
Disregard my comment about the scroll issue.  I just tried loading a world then reloading (quit to menu, load world) and the issue occurred.

You may want to disregard the entire thing, actually.  As far as I can tell, /dank/null is **not** the culprit.  I removed the /dank/null jar and tested it (load world, quit to menu, load world) and the same issue occurred.

On another note, thanks for making a great mod!

**Comment by hills1** [comment] 2017-11-24 22:58
Might even be an issue in Forge itself.  I found this: http://www.minecraftforge.net/forum/topic/61613-cannot-reload-singleplayer-world-because-of-ongoing-internal-server-transition-is-in-progress/

**Comment by ANNOYEDCHERRY** [comment] 2017-11-24 23:37
Too me these maybe separate issues, but I'm not an expert on coding.

**Comment by p455w0rd** [comment] 2017-12-08 13:01
This has finally been resolved! I will close this as the discussion has moved to #35

**Closed by p455w0rd** 2017-12-08 13:01 UTC
Labels: bug-other mod
