### ISSUE TITLE
Client crash on logging in to the server- Thermal Expansion tanks. p455w0rd.danknull.client.render.DankNullRenderer.renderItem

### ISSUE THREAD

**Issue by ProsperCraft** [p455w0rd/DankNull#147] opened 2018-12-18 00:35 UTC
https://gist.github.com/ProsperCraft/8f747ab607bad94830b861dc72fad26f

Our old friend is back.

We fixed it by opening his player file in an NBT editor and removing the tank from his dank null.

**Comment by p455w0rd** [comment] 2019-01-11 16:28
i want to believe this is valid, but I'm unable to reproduce it...it's a client crash, and perhaps I'm not experiencing it due to something being fixed on thermal's end? I'm running latest of all affectable mods (CCL, CoFH/Thermal). could you join my discord and pick up the latest in-dev copy from #dank-null in my discord and test this? I'll be uploading a new version to Curse soon, and I'd like to verify that this is no longer happening first. Thanks for the report!

**Comment by ProsperCraft** [comment] 2019-01-11 16:50
I don't have a test situation to reproduce it, it was a player on my server, I am updating TownCraft and I can hold off until you release to curse.

**Closed as completed** 2019-01-12 20:24 UTC
