### ISSUE TITLE
Game stops responding on changing extraction mode

### ISSUE THREAD

**Issue by angelnc1989** [p455w0rd/DankNull#131] opened 2018-08-13 10:35 UTC
Minecraft 1.12.2
Forge 14.23.4.2749
/dank/null 1.4.33
[log](https://paste.ubuntu.com/p/Xj5Fw42znf/)

I inserted Traverse Crag Rock Cobblestone into the /dank/null and tried to change the extraction mode. The game instantly froze.

**Comment by p455w0rd** [comment] 2018-09-30 16:11
duplicate of #130

**Closed as completed** 2018-09-30 16:13 UTC
Labels: duplicate
