### ISSUE TITLE
Duplication Bug [Version: DankNull-1.12.2-1.7.89.jar]

### ISSUE THREAD

**Issue by TheRandomCrafter83** [p455w0rd/DankNull#241] opened 2019-12-18 02:53 UTC
It could be just me, but when i place the Mk VI onto the dock, it displays an error up in the right corner, then if I mine the dock up and place it back down, a duplicate mk VI has been created. I can even pick it up. I repeated it 3 times with the same result. havent tested the other tiers except for the mk IV. there was no dupe with that tier.

**Comment by xrsquaredx** [comment] 2020-01-16 17:06
I'm using Enigmatica 2 Expert modpack and I am seeing something similar. I had to do a few more steps though but was able to dupe my mk IV as well. Maybe have them get the latest and update the modpack.

UPDATE:
I checked their mod list and they are using the latest version. Here are my steps to reproduce (maybe some can be bypassed, I don't know). I set up the docking station with a hopper pointing toward it then picked up the docking station.
1. I clicked the dank null on the ground by accident and then placed the docking station on the ground under the hopper
2. I clicked the dank null on the docking station but it appeared that nothing happened
3. I put the dank null into the hopper
4. I opened the invisible dank null that was on the docking station and added an item (this made it appear
5. I removed the dank null from the hopper
6. I exited Minecraft (esc and save/quit)
7. When I opened the game back up I still had the duped and empty dank null in my hand and the dank null on the docking station.
8. I picked up the dank null from the docking station (now I have 2 dank nulls)
9. I picked up the docking station but it looks like it has a dank null on it
10. I placed the docking station back under the hopper and it does have a dank null on it
11. I picked up the dank null from the docking station (now I have 3)

I am able to repeat steps 1-8 100% of the time but 9-11 no longer dupe the dank nulls. I hope this helps.

**Comment by DejonckheereWard** [comment] 2020-01-30 17:57
Also having a duplication glitch in Engimatica 2 Expert where if you shift+ right click the docking station with a new (no nbt tags) /dank/null block, the block duplicates into your off-hand. It doesn't work if there's already other /dank/null blocks in your inventory, or if the block you're using already has an NBT tag.

**Comment by geleugim** [comment] 2020-02-19 01:15
I am able to duplicate an emerald dank when undocking it.  It does not happen often, I posted a bug report at Simple Storage Network thinking it might be issue with Storage Links.

Using MC.Eternal pack.

**Comment by nate1989** [comment] 2020-02-26 22:57
I was having this problem in Engimatica 2 Expert. if the dank null dose not have an NBT tag and placing it in the docking station dups itself I did it a few times and it crashed the server
this was the error I got when the dank null is placed 

[16:16:52] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_211]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
        at p455w0rd.danknull.inventory.cap.CapabilityDankNull$1.readNBT(CapabilityDankNull.java:92) ~[CapabilityDankNull$1.class:?]
        at p455w0rd.danknull.inventory.cap.CapabilityDankNull$1.readNBT(CapabilityDankNull.java:26) ~[CapabilityDankNull$1.class:?]
        at net.minecraftforge.common.capabilities.Capability.readNBT(Capability.java:102) ~[Capability.class:?]
        at p455w0rd.danknull.blocks.tiles.TileDankNullDock.setDankNull(TileDankNullDock.java:148) ~[TileDankNullDock.class:?]
        at p455w0rd.danknull.blocks.BlockDankNullDock.func_180639_a(BlockDankNullDock.java:119) ~[BlockDankNullDock.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

**Comment by Twisted-Code** [comment] 2020-03-22 15:53
I'm also having a duping issue with the docking station. 

When I tried to place a freshly-crafted MK VI Dank on a freshly-crafted docking station (both crafted via AE 2's crafting terminal) after trying to hook an item conduit (from Enderio) to the empty station (newsflash: item conduits don't think the empty station is a inventory), it didn't work right. The docking station still appeared to be empty, and subsequent right clicks opened an empty dank inventory, which I at the time assumed was from the dank I was holding (although, since I can't recall if the first right-click also did this, it's more likely, given what happened next, that the item had already duped and this was actually an invisible dank on the docking station). Then, when I tried to shift-right-click the dank I was holding onto it, I instead got a duplicate dank. I was able to reproduce it multiple times with the same dank (the one that I had just crafted), but could not get it to happen with any of the duplicates and I'm hesitant to try it with any of the danks I already have filled with stuff. 

Reproduction steps (tentative; I'm not actually sure how many of these are required, or accurate for that matter, but don't have time to test further right now):
1. craft a MK VI dank (from 5 pieces, not upgrading) and a docking station (in my case I used Applied Energistics' crafting terminal but this may not be necessary)
2. Place the docking station down
3. (Possibly optional; I need to test further) place an Enderio item conduit adjacent to it (it won't connect to the empty station) and subsequently remove it in frustration (okay admittedly the frustration is probably not necessary, but let's not ignore the variables of the experiment okay : stuck_out_tongue:?)
4. Attempt to place the Dank in the station with right mouse button
5. Try again and see an empty Dank's interface
6. While the dank is still selected on your hotbar (I was still trying to place it), shift-right-click the docking station to dupe your rather expensive item!

Lastly, I see that Sqbika has already attempted to fix this on a fork; I don't know if they opened a pull request or not, but it might be worth taking a look at regardless.

**Comment by Twisted-Code** [comment] 2020-03-26 21:13
follow up on my previous comment: it seems to be something to do with freshly-crafted danks. It doesn't work on a dank that has been modified by inputting items, nor does it work on danks produced by the bugs (the ones I remove from the docking station). I also noticed that the dupe is happening when attempting to put the dank in it, not when I attempt to remove it; although invisible, I can tell, after I right-click the station with a compatible dank, that there is a duplicate because if I right-click with an empty hand, it opens the inventory of the duplicate. 
hypothesis: the duplicate is invisible because there's something wrong with your model handling code, resulting in the right-click action being aborted, but not reversed?

**Comment by Twisted-Code** [comment] 2020-03-27 18:00
apparently this is a duplicate of #262 
(...and probably a few others considering the severity of the bug. Severe bugs are more prone to redundant reporting because everyone wants them fixed)

**Comment by cjm721** [comment] 2020-03-28 22:40
Appears fixed by #263

**Closed as completed by cjm721** 2020-03-28 22:40 UTC
