### ISSUE TITLE
Items changed when moved into DN

### ISSUE THREAD

**Issue by EcksEcksEcks** [p455w0rd/DankNull#208] opened 2019-09-08 12:31 UTC
Hey,

When moving copper ingots into my DN it's turning them into pulverized iron. Any ideas what may be causing this?

**Comment by BrockWS** [comment] 2019-09-08 12:37
Duplicate of #204

**Closed as completed by BrockWS** 2019-09-08 12:37 UTC
Labels: duplicate

**Comment by EcksEcksEcks** [comment] 2019-09-08 13:23
Hold on.. You linked this to a closed issue that wasn't resolved.

**Comment by p455w0rd** [comment] 2019-09-08 13:26
it is not reproducable..sorry..it IS resolved...if you wish to provide useful information as to exactly how this is happening, I am willing to look into it...but I'm not here to teach how to write a proper report and with the infoprmation given, I cannot reproduce..therefore, it is invalid and resolved

**Comment by p455w0rd** [comment] 2019-09-08 14:16
Please be sure you are using the latest version (1.6.80)...Brock did some testing..appears to have been a bug in *.77, but is fixed...please always be 100% certain you are running the latest when you encounter a bug
