### ISSUE TITLE
Thaumcraft Vis Crystal

### ISSUE THREAD

**Issue by Kiktamo** [p455w0rd/DankNull#105] opened 2018-04-28 00:00 UTC
Just something that I noticed with the new Thaumcraft 6 on 1.12 is that if you place one of the vis crystal of an aspect in the dank null and then pick up one of another aspect it merges them together converting to whatever aspect is already in the dank null.

**Comment by Voxel-Friend** [comment] 2018-04-28 04:37
This is due to how azanor handles vis cryatals. they don't play nice with inventory tweaks either.

**Comment by p455w0rd** [comment] 2018-04-29 10:51
this is likely a dupe of #95 ..i'll leave it open for now..sorry it's taking so long to get this update pushed..I just want to be sure I have things working properly in SMP with the docking station and I'm extremely busy with other projects as well as stuff IRL..I will be getting to /dank/null soon though

**Comment by choekstr** [comment] 2018-05-05 21:14
Came here to report same thing, vis crystals are all converted to the first type you put in to the dank null.  Seems like it might indeed be a dupe of #95

**Closed as completed** 2018-05-16 14:01 UTC
Labels: duplicate
