### ISSUE TITLE
Crash Report on nesest version

### ISSUE THREAD

**Issue by dagantang** [p455w0rd/DankNull#243] opened 2019-12-20 06:37 UTC
https://paste.dimdev.org/egokocoriy.mccrash

**Comment by VendoAU** [comment] 2020-01-03 08:09
I also have a similar crash on the newest version:
https://paste.dimdev.org/casixepoci.rb

**Comment by cjm721** [comment] 2020-03-28 22:42
Duplicate of #237

**Closed as completed by cjm721** 2020-03-28 22:42 UTC
