### ISSUE TITLE
Not Voiding.

### ISSUE THREAD

**Issue by Extechs** [p455w0rd/DankNull#278] opened 2020-04-15 11:21 UTC
I updated my MC eternal Modpack on twitch mods. I and others as well are facing an issue where the Nulls are not voiding blocks after it fills up. This is on multiplayer servers and single player.

Ideas?

**Comment by HeavyDeception** [comment] 2020-04-15 11:41
The same this is happening to me I also wanted to add that its is not taking whats in it incorrectly showing blank spots were item you use are. [The blank areas are dirt and cobble and Chiseled Cobble.](https://puu.sh/FxOI2/ae2ad790af.png) I can still see how much is in it tho when I [hold it](https://puu.sh/FxOMj/ac18abeaab.png).

**Comment by cjm721** [comment] 2020-04-16 05:03
If you are on above 90 this was intentional as I rework how internals function to make less buggy before reading features.

**Comment by HeavyDeception** [comment] 2020-04-16 09:37
DankNull-1.12.2-1.7.94 so do I need to roll back one or change something in the config? Also I'm using a different mod pack. but it most likely doesn't matter for this.

**Comment by cjm721** [comment] 2020-04-16 20:18
Rollback to the latest release. I will keep my influx stuff in beta. I originally posted 92+ as release then realized that was a bad idea after the fact.

Duplicate of #282

**Closed as completed** 2020-04-16 20:18 UTC
